#!/bin/bash
# install-mac-sync.sh — one-command installer for the Mac side of the
# bi-directional Obsidian ↔ jjrpro/code sync loop.
#
# Run on your Mac:
#   bash install-mac-sync.sh [VAULT_PATH]
#
# Defaults VAULT_PATH to: ~/Documents/Obsidian/JaurxOps
#
# What it does:
#   1. Clones jjrpro/code (branch claude/jjr-ops-handoff-QHQJj) into VAULT_PATH
#      (or pulls latest if already cloned)
#   2. Writes ~/Library/LaunchAgents/com.jjr.obsidian-jaurx-sync.plist
#   3. Writes ~/.local/bin/jjr-obsidian-sync-loop.sh — runs every 60s, does:
#        a) fetch + fast-forward pull (web → Mac)
#        b) if local Obsidian edits exist: commit + push (Mac → web)
#   4. Loads the LaunchAgent
#   5. Verifies it's running and prints the log path
#
# Safe to re-run — idempotent.

set -e

VAULT_PATH="${1:-$HOME/Documents/Obsidian/JaurxOps}"
REPO_URL="https://github.com/jjrpro/code"
BRANCH="claude/jjr-ops-handoff-QHQJj"
LABEL="com.jjr.obsidian-jaurx-sync"
PLIST="$HOME/Library/LaunchAgents/${LABEL}.plist"
SYNC_SCRIPT="$HOME/.local/bin/jjr-obsidian-sync-loop.sh"
LOG_FILE="$HOME/Library/Logs/jjr-obsidian-sync.log"

# Legacy pull-only script path (cleaned up below if it exists)
OLD_PULL_SCRIPT="$HOME/.local/bin/jjr-obsidian-pull-loop.sh"

echo "[install] vault path: $VAULT_PATH"
echo "[install] repo: $REPO_URL ($BRANCH)"

# ----- 1) Clone or update the vault repo -----
mkdir -p "$(dirname "$VAULT_PATH")"
if [ -d "$VAULT_PATH/.git" ]; then
  echo "[install] vault already a git repo — pulling latest"
  git -C "$VAULT_PATH" fetch origin "$BRANCH" --quiet
  git -C "$VAULT_PATH" checkout "$BRANCH" --quiet 2>/dev/null || true
  git -C "$VAULT_PATH" pull origin "$BRANCH" --ff-only --quiet || {
    echo "[install] ⚠️  pull failed — you may have local changes. Resolve manually."
  }
else
  echo "[install] cloning fresh"
  git clone --branch "$BRANCH" --depth 1 "$REPO_URL" "$VAULT_PATH"
fi

# ----- 2) Write the bi-directional sync script -----
mkdir -p "$(dirname "$SYNC_SCRIPT")"
mkdir -p "$(dirname "$LOG_FILE")"

# Clean up legacy pull-only script if present
if [ -f "$OLD_PULL_SCRIPT" ] && [ "$OLD_PULL_SCRIPT" != "$SYNC_SCRIPT" ]; then
  rm -f "$OLD_PULL_SCRIPT"
  echo "[install] removed legacy script $OLD_PULL_SCRIPT"
fi

cat > "$SYNC_SCRIPT" <<EOF
#!/bin/bash
# Auto-generated by install-mac-sync.sh — bi-directional sync loop.
# Runs every 60s via LaunchAgent.
#
# Order of operations:
#   1) Fetch + fast-forward pull (web edits → Mac/Obsidian)
#   2) If local edits exist (Obsidian writes), commit + push (Mac → web)
#
# Push uses fetch+rebase first so it survives if the web side pushed
# in between. Rebase conflicts are surfaced in the log, not silently lost.

VAULT="$VAULT_PATH"
BRANCH="$BRANCH"

cd "\$VAULT" || exit 0
[ -d .git ] || exit 0

ts() { date '+%Y-%m-%d %H:%M:%S'; }
pulled_count=0

# ----- 1) Pull side: fetch + fast-forward -----
git fetch origin "\$BRANCH" --quiet 2>/dev/null
behind=\$(git rev-list --count HEAD.."origin/\$BRANCH" 2>/dev/null)

if [ -n "\$behind" ] && [ "\$behind" != "0" ]; then
  if git pull origin "\$BRANCH" --ff-only --quiet 2>/dev/null; then
    pulled_count=\$behind
    echo "[\$(ts)] pulled \$behind commit(s) from \$BRANCH"
  else
    echo "[\$(ts)] WARN pull blocked - local edits + remote edits diverged (handled by push step)"
  fi
fi

# ----- 2) Push side: commit + push any local Obsidian edits -----
# Skip if working tree is clean
if git diff --quiet && git diff --cached --quiet && [ -z "\$(git status --porcelain)" ]; then
  # Heartbeat: log "tick" only if no pull happened either.
  # Keeps the log alive as proof-of-life without doubling up on entries.
  if [ "\$pulled_count" = "0" ]; then
    echo "[\$(ts)] tick - up to date (HEAD: \$(git rev-parse --short HEAD))"
  fi
  exit 0
fi

git add -A 2>/dev/null
# If staging produced nothing (e.g. only ignored files changed), bail
git diff --cached --quiet && exit 0

changed=\$(git diff --cached --name-only | wc -l | tr -d ' ')
git -c commit.gpgsign=false commit -m "obsidian-mac-sync: \${changed} file(s) updated" --quiet 2>&1 >/dev/null || exit 0

# Try push; on rejection (web pushed in parallel), rebase and retry
if ! git push origin "\$BRANCH" --quiet 2>/dev/null; then
  if git pull --rebase --autostash origin "\$BRANCH" --quiet 2>/dev/null; then
    if git push origin "\$BRANCH" --quiet 2>/dev/null; then
      echo "[\$(ts)] pushed \${changed} file(s) after rebase"
    else
      echo "[\$(ts)] ⚠️  push failed after rebase — check network or auth"
    fi
  else
    git rebase --abort 2>/dev/null || true
    echo "[\$(ts)] ⚠️  rebase conflict — edit conflicts manually in \$VAULT"
  fi
else
  echo "[\$(ts)] pushed \${changed} file(s) to \$BRANCH"
fi
EOF
chmod +x "$SYNC_SCRIPT"
echo "[install] wrote $SYNC_SCRIPT"

# ----- 3) Write the LaunchAgent plist -----
mkdir -p "$(dirname "$PLIST")"
cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$SYNC_SCRIPT</string>
  </array>
  <key>StartInterval</key>
  <integer>60</integer>
  <key>RunAtLoad</key>
  <true/>
  <key>StandardOutPath</key>
  <string>$LOG_FILE</string>
  <key>StandardErrorPath</key>
  <string>$LOG_FILE</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
  </dict>
</dict>
</plist>
EOF
echo "[install] wrote $PLIST"

# ----- 4) Load (or reload) the LaunchAgent -----
if launchctl list | grep -q "$LABEL"; then
  echo "[install] LaunchAgent already loaded — reloading"
  launchctl unload "$PLIST" 2>/dev/null || true
fi
launchctl load "$PLIST"
echo "[install] launchctl loaded $LABEL"

# ----- 5) Verify -----
sleep 2
if launchctl list | grep -q "$LABEL"; then
  echo ""
  echo "✅ Obsidian sync installed and running"
  echo ""
  echo "  Vault:       $VAULT_PATH"
  echo "  Branch:      $BRANCH"
  echo "  Pull every:  60 seconds"
  echo "  Log file:    $LOG_FILE"
  echo ""
  echo "Tail the log to watch pulls in real time:"
  echo "  tail -f $LOG_FILE"
  echo ""
  echo "To stop the sync later:"
  echo "  launchctl unload $PLIST"
  echo ""
  echo "To restart after a change:"
  echo "  launchctl unload $PLIST && launchctl load $PLIST"
  echo ""
  echo "Now open Obsidian → 'Open folder as vault' → pick:"
  echo "  $VAULT_PATH"
else
  echo "❌ LaunchAgent failed to register. Check log: $LOG_FILE"
  exit 1
fi
