# install-windows-sync.ps1 - Windows equivalent of install-mac-sync.sh.
# One-command installer for the bi-directional Obsidian <-> jjrpro/code sync.
#
# Run from PowerShell (does NOT need admin):
#   powershell -ExecutionPolicy Bypass -File install-windows-sync.ps1
#
# Optional first argument overrides the vault path:
#   powershell -ExecutionPolicy Bypass -File install-windows-sync.ps1 "C:\Users\John\Obsidian\JaurxOps"
#
# What it does:
#   1. Clones jjrpro/code (branch claude/jjr-ops-handoff-QHQJj) into the vault path
#      (or pulls latest if already cloned)
#   2. Writes %USERPROFILE%\.local\bin\jjr-obsidian-sync-loop.ps1
#   3. Registers a Windows Scheduled Task that runs the script every 1 minute
#   4. Triggers the task once to verify and prints the log path
#
# Safe to re-run. Re-running unregisters the old task and re-installs.
#
# ASCII-only on purpose: Windows PowerShell 5.1 reads .ps1 files as ANSI
# unless a UTF-8 BOM is present, and breaks on non-ASCII glyphs.

param(
    [string]$VaultPath = "$env:USERPROFILE\Documents\Obsidian\JaurxOps"
)

$ErrorActionPreference = "Stop"

$RepoUrl    = "https://github.com/jjrpro/code"
$Branch     = "claude/jjr-ops-handoff-QHQJj"
$TaskName   = "JJR-Obsidian-Sync"
$ScriptDir  = "$env:USERPROFILE\.local\bin"
$SyncScript = "$ScriptDir\jjr-obsidian-sync-loop.ps1"
$LogDir     = "$env:USERPROFILE\.local\logs"
$LogFile    = "$LogDir\jjr-obsidian-sync.log"

Write-Host "[install] vault path: $VaultPath"
Write-Host "[install] repo:       $RepoUrl ($Branch)"

# ----- Sanity: git on PATH? -----
if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    Write-Host "[install] ERROR: git not found on PATH." -ForegroundColor Red
    Write-Host "  Install Git for Windows: https://git-scm.com/download/win"
    exit 1
}

# ----- 1) Clone or update the vault repo -----
$VaultParent = Split-Path -Parent $VaultPath
if (-not (Test-Path $VaultParent)) {
    New-Item -ItemType Directory -Path $VaultParent | Out-Null
}

if (Test-Path "$VaultPath\.git") {
    Write-Host "[install] vault already a git repo - pulling latest"
    git -C $VaultPath fetch origin $Branch --quiet
    git -C $VaultPath checkout $Branch --quiet 2>$null
    git -C $VaultPath pull origin $Branch --ff-only --quiet
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[install] WARNING: pull failed. You may have local changes. Resolve manually." -ForegroundColor Yellow
    }
} else {
    Write-Host "[install] cloning fresh"
    git clone --branch $Branch --depth 1 $RepoUrl $VaultPath
}

# ----- 2) Write the bi-directional sync script -----
if (-not (Test-Path $ScriptDir)) { New-Item -ItemType Directory -Path $ScriptDir | Out-Null }
if (-not (Test-Path $LogDir))    { New-Item -ItemType Directory -Path $LogDir    | Out-Null }

# Build the sync-loop script content via single-quoted here-string so that
# $-references are written literally (we want them resolved at task-run time,
# not at install time). Two placeholders (__VAULT__, __BRANCH__) are
# substituted below before writing the file.
$SyncBodyTemplate = @'
# Auto-generated by install-windows-sync.ps1
# Bi-directional sync loop. Triggered every 1 minute by JJR-Obsidian-Sync.
#
# Order of operations:
#   1) Fetch + fast-forward pull (web edits -> local Obsidian vault)
#   2) If local edits exist (Obsidian writes), commit + push (local -> web)
#
# Push uses fetch+rebase first so it survives a parallel push from web.
# Rebase conflicts are surfaced in the log, not silently lost.

$ErrorActionPreference = 'SilentlyContinue'

$Vault   = '__VAULT__'
$Branch  = '__BRANCH__'
$LogFile = '__LOGFILE__'

function Write-Log($msg) {
    $ts = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    "$ts  $msg" | Out-File -FilePath $LogFile -Append -Encoding utf8
}

if (-not (Test-Path "$Vault\.git")) { exit 0 }
Set-Location $Vault

# ----- 1) Pull side: fetch + fast-forward -----
git fetch origin $Branch --quiet
$behind = (git rev-list --count "HEAD..origin/$Branch" 2>$null)

if ($behind -and $behind -ne '0') {
    git pull origin $Branch --ff-only --quiet
    if ($LASTEXITCODE -eq 0) {
        Write-Log "pulled $behind commit(s) from $Branch"
    } else {
        Write-Log "WARN: pull blocked - local + remote diverged (handled by push step)"
    }
}

# ----- 2) Push side: commit + push any local Obsidian edits -----
$status = (git status --porcelain)
if ([string]::IsNullOrWhiteSpace($status)) { exit 0 }

git add -A
git diff --cached --quiet
if ($LASTEXITCODE -eq 0) { exit 0 }  # nothing staged

$changed = ((git diff --cached --name-only) | Measure-Object -Line).Lines
git -c commit.gpgsign=false commit -m "obsidian-windows-sync: $changed file(s) updated" --quiet
if ($LASTEXITCODE -ne 0) { exit 0 }

# Try push; on rejection, rebase and retry
git push origin $Branch --quiet
if ($LASTEXITCODE -ne 0) {
    git pull --rebase --autostash origin $Branch --quiet
    if ($LASTEXITCODE -eq 0) {
        git push origin $Branch --quiet
        if ($LASTEXITCODE -eq 0) {
            Write-Log "pushed $changed file(s) after rebase"
        } else {
            Write-Log "WARN: push failed after rebase - check network or auth"
        }
    } else {
        git rebase --abort
        Write-Log "WARN: rebase conflict - resolve manually in $Vault"
    }
} else {
    Write-Log "pushed $changed file(s) to $Branch"
}
'@

$SyncBody = $SyncBodyTemplate `
    -replace '__VAULT__',   [Regex]::Escape($VaultPath).Replace('\\','\') `
    -replace '__BRANCH__',  $Branch `
    -replace '__LOGFILE__', [Regex]::Escape($LogFile).Replace('\\','\')

# Write as UTF-8 WITH BOM so Windows PowerShell 5.1 parses it correctly
$Utf8Bom = New-Object System.Text.UTF8Encoding($true)
[System.IO.File]::WriteAllText($SyncScript, $SyncBody, $Utf8Bom)
Write-Host "[install] wrote $SyncScript"

# ----- 3) Register the Scheduled Task via schtasks.exe -----
# We use schtasks.exe (not Register-ScheduledTask) because the cmdlet
# requires admin to register at the default root TaskPath, even for
# user-scope tasks with Interactive principals. schtasks.exe handles
# user-scope tasks cleanly without elevation.

# Remove any prior registration so re-install is idempotent.
$existing = schtasks /Query /TN $TaskName 2>$null
if ($LASTEXITCODE -eq 0) {
    Write-Host "[install] task already exists - removing for clean re-install"
    schtasks /Delete /TN $TaskName /F | Out-Null
}

$TaskCmd = "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$SyncScript`""

schtasks /Create `
    /TN $TaskName `
    /TR $TaskCmd `
    /SC MINUTE /MO 1 `
    /F | Out-Null

if ($LASTEXITCODE -ne 0) {
    Write-Host "[install] ERROR: schtasks /Create failed (exit $LASTEXITCODE)" -ForegroundColor Red
    exit 1
}

Write-Host "[install] registered scheduled task: $TaskName"

# ----- 4) Trigger once to verify -----
schtasks /Run /TN $TaskName | Out-Null
Start-Sleep -Seconds 3

schtasks /Query /TN $TaskName 2>$null | Out-Null
if ($LASTEXITCODE -eq 0) {
    Write-Host ""
    Write-Host "Obsidian sync installed and running" -ForegroundColor Green
    Write-Host ""
    Write-Host "  Vault:        $VaultPath"
    Write-Host "  Branch:       $Branch"
    Write-Host "  Run every:    1 minute"
    Write-Host "  Log file:     $LogFile"
    Write-Host "  Task name:    $TaskName"
    Write-Host ""
    Write-Host "Tail the log to watch syncs in real time:"
    Write-Host "  Get-Content -Path `"$LogFile`" -Wait"
    Write-Host ""
    Write-Host "Manage the task:"
    Write-Host "  Stop:      schtasks /Change /TN $TaskName /DISABLE"
    Write-Host "  Resume:    schtasks /Change /TN $TaskName /ENABLE"
    Write-Host "  Remove:    schtasks /Delete /TN $TaskName /F"
    Write-Host "  Status:    schtasks /Query /TN $TaskName /V /FO LIST"
    Write-Host ""
    Write-Host "Now open Obsidian -> 'Open folder as vault' -> pick:"
    Write-Host "  $VaultPath"
} else {
    Write-Host "Scheduled task failed to register. Check Task Scheduler." -ForegroundColor Red
    exit 1
}
