# install-windows-sync.ps1 — Windows equivalent of install-mac-sync.sh.
# One-command installer for the bi-directional Obsidian <-> jjrpro/code sync.
#
# Run from PowerShell (does NOT need admin):
#   powershell -ExecutionPolicy Bypass -File install-windows-sync.ps1
#
# Optional first argument overrides the vault path:
#   powershell -ExecutionPolicy Bypass -File install-windows-sync.ps1 "C:\Users\John\Obsidian\JaurxOps"
#
# What it does:
#   1. Clones jjrpro/code (branch claude/jjr-ops-handoff-QHQJj) into the vault path
#      (or pulls latest if already cloned)
#   2. Writes %USERPROFILE%\.local\bin\jjr-obsidian-sync-loop.ps1
#   3. Registers a Windows Scheduled Task that runs the script every 1 minute
#   4. Triggers the task once to verify and prints the log path
#
# Safe to re-run — idempotent. Re-running unregisters the old task and re-installs.

param(
    [string]$VaultPath = "$env:USERPROFILE\Documents\Obsidian\JaurxOps"
)

$ErrorActionPreference = "Stop"

$RepoUrl    = "https://github.com/jjrpro/code"
$Branch     = "claude/jjr-ops-handoff-QHQJj"
$TaskName   = "JJR-Obsidian-Sync"
$ScriptDir  = "$env:USERPROFILE\.local\bin"
$SyncScript = "$ScriptDir\jjr-obsidian-sync-loop.ps1"
$LogDir     = "$env:USERPROFILE\.local\logs"
$LogFile    = "$LogDir\jjr-obsidian-sync.log"

Write-Host "[install] vault path: $VaultPath"
Write-Host "[install] repo:       $RepoUrl ($Branch)"

# ----- Sanity: git on PATH? -----
if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    Write-Host "[install] ERROR: git not found on PATH." -ForegroundColor Red
    Write-Host "  Install Git for Windows: https://git-scm.com/download/win"
    exit 1
}

# ----- 1) Clone or update the vault repo -----
$VaultParent = Split-Path -Parent $VaultPath
if (-not (Test-Path $VaultParent)) { New-Item -ItemType Directory -Path $VaultParent | Out-Null }

if (Test-Path "$VaultPath\.git") {
    Write-Host "[install] vault already a git repo — pulling latest"
    git -C $VaultPath fetch origin $Branch --quiet
    git -C $VaultPath checkout $Branch --quiet 2>$null
    try {
        git -C $VaultPath pull origin $Branch --ff-only --quiet
    } catch {
        Write-Host "[install] WARNING: pull failed — you may have local changes. Resolve manually." -ForegroundColor Yellow
    }
} else {
    Write-Host "[install] cloning fresh"
    git clone --branch $Branch --depth 1 $RepoUrl $VaultPath
}

# ----- 2) Write the bi-directional sync script -----
if (-not (Test-Path $ScriptDir)) { New-Item -ItemType Directory -Path $ScriptDir | Out-Null }
if (-not (Test-Path $LogDir))    { New-Item -ItemType Directory -Path $LogDir    | Out-Null }

$SyncBody = @"
# Auto-generated by install-windows-sync.ps1 — bi-directional sync loop.
# Triggered every 1 minute by the JJR-Obsidian-Sync scheduled task.
#
# Order of operations:
#   1) Fetch + fast-forward pull (web edits -> local Obsidian vault)
#   2) If local edits exist (Obsidian writes), commit + push (local -> web)
#
# Push uses fetch+rebase first so it survives a parallel push from web.
# Rebase conflicts are surfaced in the log, not silently lost.

`$ErrorActionPreference = 'SilentlyContinue'

`$Vault    = '$VaultPath'
`$Branch   = '$Branch'
`$LogFile  = '$LogFile'

function ts { (Get-Date -Format 'yyyy-MM-dd HH:mm:ss') }
function log(`$msg) { "`$(ts)  `$msg" | Out-File -FilePath `$LogFile -Append -Encoding utf8 }

if (-not (Test-Path "`$Vault\.git")) { exit 0 }
Set-Location `$Vault

# ----- 1) Pull side: fetch + fast-forward -----
git fetch origin `$Branch --quiet
`$behind = (git rev-list --count "HEAD..origin/`$Branch" 2>`$null)

if (`$behind -and `$behind -ne '0') {
    git pull origin `$Branch --ff-only --quiet
    if (`$LASTEXITCODE -eq 0) {
        log "pulled `$behind commit(s) from `$Branch"
    } else {
        log "WARN: pull blocked — local + remote diverged (handled by push step)"
    }
}

# ----- 2) Push side: commit + push any local Obsidian edits -----
`$status = (git status --porcelain)
if ([string]::IsNullOrWhiteSpace(`$status)) { exit 0 }

git add -A
git diff --cached --quiet
if (`$LASTEXITCODE -eq 0) { exit 0 }  # nothing staged

`$changed = ((git diff --cached --name-only) | Measure-Object -Line).Lines
git -c commit.gpgsign=false commit -m "obsidian-windows-sync: `$changed file(s) updated" --quiet
if (`$LASTEXITCODE -ne 0) { exit 0 }

# Try push; on rejection, rebase and retry
git push origin `$Branch --quiet
if (`$LASTEXITCODE -ne 0) {
    git pull --rebase --autostash origin `$Branch --quiet
    if (`$LASTEXITCODE -eq 0) {
        git push origin `$Branch --quiet
        if (`$LASTEXITCODE -eq 0) {
            log "pushed `$changed file(s) after rebase"
        } else {
            log "WARN: push failed after rebase — check network or auth"
        }
    } else {
        git rebase --abort
        log "WARN: rebase conflict — resolve manually in `$Vault"
    }
} else {
    log "pushed `$changed file(s) to `$Branch"
}
"@

Set-Content -Path $SyncScript -Value $SyncBody -Encoding UTF8
Write-Host "[install] wrote $SyncScript"

# ----- 3) Register the Scheduled Task -----
# Unregister if already exists (idempotent re-install)
if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Write-Host "[install] task already exists — unregistering for clean re-install"
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

$Action = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$SyncScript`""

# Trigger: run at logon + every 1 minute indefinitely
$Trigger = New-ScheduledTaskTrigger -AtLogOn
$Trigger.Repetition = (New-ScheduledTaskTrigger -Once -At (Get-Date) `
    -RepetitionInterval (New-TimeSpan -Minutes 1) `
    -RepetitionDuration (New-TimeSpan -Days 9999)).Repetition

$Settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 5)

$Principal = New-ScheduledTaskPrincipal `
    -UserId $env:USERNAME `
    -LogonType Interactive `
    -RunLevel Limited

Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $Action `
    -Trigger $Trigger `
    -Settings $Settings `
    -Principal $Principal `
    -Description "Bi-directional sync between Obsidian vault and jjrpro/code repo (every 1 min)" `
    | Out-Null

Write-Host "[install] registered scheduled task: $TaskName"

# ----- 4) Trigger once to verify -----
Start-ScheduledTask -TaskName $TaskName
Start-Sleep -Seconds 3

$task = Get-ScheduledTask -TaskName $TaskName
if ($task) {
    Write-Host ""
    Write-Host "Obsidian sync installed and running" -ForegroundColor Green
    Write-Host ""
    Write-Host "  Vault:        $VaultPath"
    Write-Host "  Branch:       $Branch"
    Write-Host "  Run every:    1 minute"
    Write-Host "  Log file:     $LogFile"
    Write-Host "  Task name:    $TaskName"
    Write-Host ""
    Write-Host "Tail the log to watch syncs in real time:"
    Write-Host "  Get-Content -Path `"$LogFile`" -Wait"
    Write-Host ""
    Write-Host "Manage the task:"
    Write-Host "  Stop:      Disable-ScheduledTask -TaskName $TaskName"
    Write-Host "  Resume:    Enable-ScheduledTask  -TaskName $TaskName"
    Write-Host "  Remove:    Unregister-ScheduledTask -TaskName $TaskName -Confirm:`$false"
    Write-Host ""
    Write-Host "Now open Obsidian -> 'Open folder as vault' -> pick:"
    Write-Host "  $VaultPath"
} else {
    Write-Host "Scheduled task failed to register. Check Task Scheduler." -ForegroundColor Red
    exit 1
}
