#!/bin/bash
# install-mac-sync.sh — one-command installer for the Mac side of the
# repo → Obsidian vault sync loop.
#
# Run on your Mac:
#   bash install-mac-sync.sh [VAULT_PATH]
#
# Defaults VAULT_PATH to: ~/Documents/Obsidian/JaurxOps
#
# What it does:
#   1. Clones jjrpro/code (branch claude/jjr-ops-handoff-QHQJj) into VAULT_PATH
#      (or pulls latest if already cloned)
#   2. Writes ~/Library/LaunchAgents/com.jjr.obsidian-jaurx-sync.plist
#   3. Writes ~/.local/bin/jjr-obsidian-pull-loop.sh (the actual pull script)
#   4. Loads the LaunchAgent so it pulls every 60 sec
#   5. Verifies it's running and prints the log path
#
# Safe to re-run — idempotent.

set -e

VAULT_PATH="${1:-$HOME/Documents/Obsidian/JaurxOps}"
REPO_URL="https://github.com/jjrpro/code"
BRANCH="claude/jjr-ops-handoff-QHQJj"
LABEL="com.jjr.obsidian-jaurx-sync"
PLIST="$HOME/Library/LaunchAgents/${LABEL}.plist"
PULL_SCRIPT="$HOME/.local/bin/jjr-obsidian-pull-loop.sh"
LOG_FILE="$HOME/Library/Logs/jjr-obsidian-sync.log"

echo "[install] vault path: $VAULT_PATH"
echo "[install] repo: $REPO_URL ($BRANCH)"

# ----- 1) Clone or update the vault repo -----
mkdir -p "$(dirname "$VAULT_PATH")"
if [ -d "$VAULT_PATH/.git" ]; then
  echo "[install] vault already a git repo — pulling latest"
  git -C "$VAULT_PATH" fetch origin "$BRANCH" --quiet
  git -C "$VAULT_PATH" checkout "$BRANCH" --quiet 2>/dev/null || true
  git -C "$VAULT_PATH" pull origin "$BRANCH" --ff-only --quiet || {
    echo "[install] ⚠️  pull failed — you may have local changes. Resolve manually."
  }
else
  echo "[install] cloning fresh"
  git clone --branch "$BRANCH" --depth 1 "$REPO_URL" "$VAULT_PATH"
fi

# ----- 2) Write the pull-loop script -----
mkdir -p "$(dirname "$PULL_SCRIPT")"
mkdir -p "$(dirname "$LOG_FILE")"

cat > "$PULL_SCRIPT" <<EOF
#!/bin/bash
# Auto-generated by install-mac-sync.sh — pulls latest from origin/$BRANCH
# every time the LaunchAgent fires (every 60s).
# Fast-forward only, so local edits in the Obsidian vault are NEVER overwritten.

VAULT="$VAULT_PATH"
BRANCH="$BRANCH"

cd "\$VAULT" || exit 0
[ -d .git ] || exit 0

git fetch origin "\$BRANCH" --quiet 2>/dev/null
behind=\$(git rev-list --count HEAD.."origin/\$BRANCH" 2>/dev/null)

if [ "\$behind" = "0" ] || [ -z "\$behind" ]; then
  exit 0
fi

if git pull origin "\$BRANCH" --ff-only --quiet 2>/dev/null; then
  echo "[\$(date '+%Y-%m-%d %H:%M:%S')] pulled \$behind commit(s) from \$BRANCH"
else
  echo "[\$(date '+%Y-%m-%d %H:%M:%S')] ⚠️  cannot fast-forward — local changes block pull"
fi
EOF
chmod +x "$PULL_SCRIPT"
echo "[install] wrote $PULL_SCRIPT"

# ----- 3) Write the LaunchAgent plist -----
mkdir -p "$(dirname "$PLIST")"
cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$PULL_SCRIPT</string>
  </array>
  <key>StartInterval</key>
  <integer>60</integer>
  <key>RunAtLoad</key>
  <true/>
  <key>StandardOutPath</key>
  <string>$LOG_FILE</string>
  <key>StandardErrorPath</key>
  <string>$LOG_FILE</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
  </dict>
</dict>
</plist>
EOF
echo "[install] wrote $PLIST"

# ----- 4) Load (or reload) the LaunchAgent -----
if launchctl list | grep -q "$LABEL"; then
  echo "[install] LaunchAgent already loaded — reloading"
  launchctl unload "$PLIST" 2>/dev/null || true
fi
launchctl load "$PLIST"
echo "[install] launchctl loaded $LABEL"

# ----- 5) Verify -----
sleep 2
if launchctl list | grep -q "$LABEL"; then
  echo ""
  echo "✅ Obsidian sync installed and running"
  echo ""
  echo "  Vault:       $VAULT_PATH"
  echo "  Branch:      $BRANCH"
  echo "  Pull every:  60 seconds"
  echo "  Log file:    $LOG_FILE"
  echo ""
  echo "Tail the log to watch pulls in real time:"
  echo "  tail -f $LOG_FILE"
  echo ""
  echo "To stop the sync later:"
  echo "  launchctl unload $PLIST"
  echo ""
  echo "To restart after a change:"
  echo "  launchctl unload $PLIST && launchctl load $PLIST"
  echo ""
  echo "Now open Obsidian → 'Open folder as vault' → pick:"
  echo "  $VAULT_PATH"
else
  echo "❌ LaunchAgent failed to register. Check log: $LOG_FILE"
  exit 1
fi
